### ISSUE TITLE
exclusive expand is not working

### ISSUE THREAD

**Issue by yasirmturk** [appsome/AccordionView#19]
i want to expand only one section at a time

**Comment by suda** [comment]
You can do it by setting `[accordion setAllowsMultipleSelection:NO]`.

**Comment by yasirmturk** [comment]
does not works.. all three sections are expanded in the example project

**Comment by suda** [comment]
In [line 70 of ViewController.m](https://github.com/appsome/AccordionView/blob/master/Example/test/ViewController.m#L70) is set to `YES`. Change it to `NO` and you'll have this behaviour: 
![](http://cl.ly/image/3Z0o1K1p1k3Q/Screen%20Recording%202015-01-12%20at%2003.49%20pm.gif)

**Comment by yasirmturk** [comment]
got it i was setting in the beginning :)
