### ISSUE TITLE
Sector disappears

### ISSUE THREAD

**Issue by liblib-fib** [appsome/AccordionView#21]
1) When the minValue and maxValue are the same the slider disappears - attached image for demonstration.
2) In my opinion, the property numbersAfterPoint should be per section not as it is now all or nothing
![screen shot 2015-01-30 at 16 27 28](https://cloud.githubusercontent.com/assets/9645306/5977045/f622154c-a89c-11e4-9c0e-1f776a85fe1b.png)

**Comment by suda** [comment]
@liblib-fib are you sure this issue was supposed to be in this repo? It seems that you're talking about different control :)

**Comment by liblib-fib** [comment]
Oooopss @suda you are right :$ 
how do i delete the issue

**Comment by suda** [comment]
I don't think you can. I'll close it :)
